# Generated by Django 3.2.7 on 2021-10-14 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20211014_1754'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsCeleryTasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=300)),
                ('image', models.ImageField(blank=True, null=True, upload_to='news_pics/%Y/%m/%d')),
                ('url', models.URLField(blank=True, null=True)),
                ('lastmod', models.DateTimeField(blank=True, null=True)),
                ('content', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='News',
        ),
    ]
