# Generated by Django 3.2.7 on 2021-10-14 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20211014_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newscelerytasks',
            name='task_id',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
